// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abpxitlgresjdiwpmzbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicHhpdGxncmVzamRpd3BtemJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NjgzMjUsImV4cCI6MjA5NDI0NDMyNX0.mp2AeEzAD4bPrzuFXdBncgTAxfFqjdbVdhnhxYnMGug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});